language: go

install: true

jobs:
  include:
  - &test-nix
    name: "Testing: Bionic, go 1.11"
    stage: test
    script: make test
    os: linux
    dist: bionic
    go: 1.11.x
    env:
    - CACHE_NAME=BIONIC_1.11

  - <<: *test-nix
    name: "Testing: Bionic, go 1.12"
    go: 1.12.x
    script:
    - make shellcheck
    - make test
    env:
    - CACHE_NAME=BIONIC_1.12

  - <<: *test-nix
    name: "Testing: MacOS, go 1.12"
    os: osx
    go: 1.12.x
    env:
    - CACHE_NAME=MACOS_1.12

  - stage: test
    name: "Testing: Windows, go 1.12"
    os: windows
    go: 1.12.x
    script: ./scripts/test.sh
    env:
    - CACHE_NAME=WINDOWS_1.12

