language: go

jobs:
  include:
    - &test-nix
      stage: test
      sudo: false
      script:
      - make test
      os: linux
      dist: bionic
      go: 1.11.x
      env:
        - CACHE_NAME=BIONIC_1.11

    - <<: *test-nix
      go: 1.12.x
      script:
      - make shellcheck
      - make test
      env:
        - CACHE_NAME=BIONIC_1.12

    - <<: *test-nix
      os: osx
      go: 1.12.x
      env:
        - CACHE_NAME=MACOS_1.12

    - stage: test
      os: windows
      go: 1.12.x
      script: ./scripts/test.sh
      env:
        - CACHE_NAME=WINDOWS_1.12

install: true

