language: go

install: true

stages:
- test
- deploy
- name: deploy
  if: |
    branch = master AND \
    repo = digitalocean/doctl

notifications:
  slack:
    rooms:
      secure: NR3+H9V0/RAIS98iRqcpoDe9u8d9xMnNVT5EhwRgIiEqtONUUlHWVQaJ0ZS+fzQPHlErhAflGYSLg4L6CStF3UQoojlG6l46d9FQ3WiKFa2YAUtyoOXnOUj8AMPtjfJXwgHDxnOKcZ7RpQWg0uFMG7J8z2I3Mtm0B2MlLmwBa1jPzUkfQDKAjD1h0new7+KoRCaEQLWJA5T/nnyL4gtwjB7lBcr04SDTw91DE/mniT9Jr38UXv8MwOURmm/p5nvlG1blTopLjMWE6F2sOBj4kaDkkizcxUseRsyhu+rFPEFo9X1rPg1gxXW9lKL1JV9JFO29aHe1ZN6T0mSCraYUgqa3UaN3NiYVep/wye8KpMxJ6AiqpGvWP6ABAojlEiQkbKNvklhzKpnqwSQxm8K/mzK8kqOUMzQfEEVdUife5e0SdIk67zeCzu4PZLBJIj661XQzM4zJRy0FgmxyPKWrA8e8RimSzaT1geea96jvCwmG1VfJz+DRV2WFUwg9YIh9Xvb20q0yodvGczZU7AA0AIrePHXntFkjfRB7jQ8RFGwrVL3UqKLo6t2hforrbV0ll1EVRPZ3uUYY/tfYE2z/GNL10dcnzjlW+WYTg3ZA/6GtnsCT6GpaeKUxF9GvOEzQDIG2BwHFfQYTPuXIdFOFqKrMkdz4V+Ak/wviNBD3xrU=
    on_pull_requests: false
    os_success: change
    on_failure: always

jobs:
  include:
  - &test-nix
    name: "Testing: Bionic, go 1.11"
    stage: test
    script: make test
    dist: bionic
    go: 1.11.x
    env:
    - CACHE_NAME=BIONIC_1.11

  - <<: *test-nix
    name: "Testing: Bionic, go 1.12"
    go: 1.12.x
    script:
    - make shellcheck
    - make test
    env:
    - CACHE_NAME=BIONIC_1.12

  - <<: *test-nix
    name: "Testing: MacOS, go 1.12"
    os: osx
    go: 1.12.x
    env:
    - CACHE_NAME=MACOS_1.12

  - stage: test
    name: "Testing: Windows, go 1.12"
    os: windows
    go: 1.12.x
    script: ./scripts/test.sh
    env:
    - CACHE_NAME=WINDOWS_1.12

  - stage: deploy
    script: echo "deploying"
    dist: bionic
    go: 1.12.x
    services: docker
    env:
    - CACHE_NAME=DEPLOY
    before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login --username sammytheshark --password-stdin
    - make _build_snap
    deploy:
    - provider: script
      script: curl -sL https://git.io/goreleaser | bash
      skip_cleanup: true
      on:
        tags: true
    - provider: snap
      channel: stable
      snap: doctl_v*.snap
      skip_cleanup: true
      on:
        tags: true
    - provider: snap
      channel: candidate
      snap: doctl_v*.snap
      skip_cleanup: true
